##
##
## java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l typescript-angular -o src/contract --additional-properties ngVersion=8.3.8
##
##
swagger: '2.0'
info:
  version: 4.1.12-02-SNAPSHOT
  title: Contract
  description: Articles contract
host: 'localhost:44387'
basePath: /api
produces:
  - application/json
  
tags:
  - name: category
    description: categories service
  - name: article 
    description: articles service
  - name: user
    description: users service 

paths:
  /categories:
    get:
      operationId: getCategories
      tags:
        - category
      summary: categories
      consumes: 
        - application/json
      responses:
        '200':
          description: get all categiries
          schema: 
            type: array
            items: 
              $ref: '#/definitions/Category'
    post:
      operationId: postCategory
      tags:
        - category
      summary: add new category
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: category
          description: create Category
          schema:
            $ref: '#/definitions/Category'
      responses:
        '201':
          description: category`ve been created
    
  /categories/{id}:
    get:
      operationId: getCategory
      tags:
        - category
      summary: get category by id
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: get category by id
          required: true
          type: integer
      responses:
        '200':
          description: succsess
          schema:
            $ref: '#/definitions/Category'

  /users:
    get:
      operationId: getUsers
      tags:
        - user
      summary: get all users
      responses:
        '200':
          description: succsess
          schema: 
            type: array
            items: 
              $ref: '#/definitions/User'
        '403':
          description: does not created yeat

  /articles:
    get:
      operationId: getArticles
      tags:
        - article
      summary: get articles
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: category
          description: get articles by category
          type: integer
          format: int32
          required: false
        - in: query
          name: limit
          description: maximum number of records to return
          type: integer
          format: int32
          default: 10
          minimum: 0
          maximum: 50
          required: false
        - in: header
          name : AuthToken
          description: authorization token
          type: string
          required: false
      responses:
        '200':
          description: articles mathching criteria
          schema:
            type: array
            items: 
              $ref: '#/definitions/Article'
        '400':
          description: bad input parameter

  /createArticle:
    post:
      operationId: postArticle
      tags:
        - article
      summary: add new article
      consumes: 
        - application/json
      parameters:
        - in: body
          name: article
          description: new article
          schema:
            $ref: '#/definitions/Article'
        - in: body
          name : AuthToken
          description: authorization token
          schema:
            $ref: '#/definitions/AuthToken'
          required: true
      responses:
        '201':
          description: category`ve been created
      deprecated: false

  /articles/{id}:
    get:
      operationId: getArticle
      tags:
        - article
      summary: get article by id
      parameters:
        - name: id
          in: path
          description: get article by id
          required: true
          type: integer
        - name : AuthToken
          in: query
          description: authorization token
          type: string
          required: false
      responses:
        '200':
          description: article with id
          schema: 
            type: object
            items: 
              $ref: '#/definitions/Article'
        '400':
          description: there are no article with given id

definitions:
  Category:
    type: "object"
    properties:
        id:
            type: integer
            format: int32
        title:
            type: "string"
            format: string
    required:
      - id
      - title    
    example:
      id: 1
      title: 'sus'

  User:
    type: object
    properties:
      id: 
        type: integer
        format: int64
      username: 
        type: string
        format: string
      firstname: 
        type: string
        format: string
      surname: 
        type: string
        format: string
        description: surname
      userRole:
        $ref: '#/definitions/UserRole'
        description: enum, which describe role of the user
    required:
      - id
      - username
      - firstname
      - surname
      - userRole 

  Article:
    type: object
    properties: 
      id: 
        type: integer
        format: int32
      title:
        type: "string"
      author:
        $ref: '#/definitions/User'
      category: 
        $ref: '#/definitions/Category'
      content: 
        type: string
      creationDate: 
        type: string
        format: date-time
    required:
      - id
      - title
      - author
      - category
      - content
      - creationDate

  UserRole:
    type: string
    enum:
      - FirstDegree
      - SecondDegree 
      - ThirdDegree
      - Admin
  AccountCredentials:
    type: object
    properties: 
      username:
        type: string
      password: 
        type: string
        format: password
  AuthToken:
    type: object
    properties: 
      user:
        $ref: '#/definitions/User'
      expirationTime: 
        type: string
        format: date-time